// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwaIEyJ432WB3ar8lveP5VfKYAXLrIuHI',
    appId: '1:698853133099:web:b665f955792b97267b136e',
    messagingSenderId: '698853133099',
    projectId: 'interviewsetup-6a311',
    authDomain: 'interviewsetup-6a311.firebaseapp.com',
    storageBucket: 'interviewsetup-6a311.appspot.com',
    measurementId: 'G-G94Z5X1L44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEPh6Vd7hoCPtGeY8SE8YGw1DFY1nAhpo',
    appId: '1:698853133099:android:37cc7beccc3c80937b136e',
    messagingSenderId: '698853133099',
    projectId: 'interviewsetup-6a311',
    storageBucket: 'interviewsetup-6a311.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcosbTzkVAz_4X8sPMHTw2kF-HgLVNXWY',
    appId: '1:698853133099:ios:5fe046af3487154b7b136e',
    messagingSenderId: '698853133099',
    projectId: 'interviewsetup-6a311',
    storageBucket: 'interviewsetup-6a311.appspot.com',
    androidClientId: '698853133099-sjiao8ost3cq97hl16l0e233i9co1td0.apps.googleusercontent.com',
    iosClientId: '698853133099-8ur3k6g9o64c261fnb50lolf05tru6ft.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterIterviewTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcosbTzkVAz_4X8sPMHTw2kF-HgLVNXWY',
    appId: '1:698853133099:ios:5fe046af3487154b7b136e',
    messagingSenderId: '698853133099',
    projectId: 'interviewsetup-6a311',
    storageBucket: 'interviewsetup-6a311.appspot.com',
    androidClientId: '698853133099-sjiao8ost3cq97hl16l0e233i9co1td0.apps.googleusercontent.com',
    iosClientId: '698853133099-8ur3k6g9o64c261fnb50lolf05tru6ft.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterIterviewTask',
  );
}
